/**
 * Screenshots the two CV sheets from /cv-v2/sheets into
 * public/cv-v2/page-1.png and page-2.png — the textures mapped onto the
 * bending paper meshes of the /cv-v2 WebGL scene — and measures every
 * <a> tag's rect into components/cv-v2/cv-links.generated.ts, which the
 * scene uses to overlay real, focusable links on top of the paper. Re-run
 * after editing the CV content in components/cv-v2/cv-sheets.tsx.
 *
 * Usage:
 *   bun run cv:textures                      # spawns a dev server, renders, exits
 *   CV_PDF_BASE_URL=http://host bun ...      # renders against a running server
 */

import { spawn } from "node:child_process";
import { mkdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { chromium } from "@playwright/test";

const OUTPUT_DIR = resolve(import.meta.dirname, "../public/cv-v2");
const LINKS_FILE = resolve(
  import.meta.dirname,
  "../components/cv-v2/cv-links.generated.ts"
);
const SHEETS_PATH = "/cv-v2/sheets";
const PORT = 3211;
const SERVER_READY_TIMEOUT_MS = 120_000;
const PAGE_LOAD_TIMEOUT_MS = 120_000;
const POLL_INTERVAL_MS = 500;
// Text is baked into this raster texture rather than staying vector like
// real HTML, so it has a sharpness ceiling — push it high enough that
// zooming in (browser zoom or a close camera) doesn't visibly soften it.
const TEXTURE_SCALE = 3;

const externalBaseUrl = process.env.CV_PDF_BASE_URL;

const delay = (ms: number) =>
  new Promise<void>((resolvePoll) => setTimeout(resolvePoll, ms));

async function waitForServer(baseUrl: string) {
  const deadline = Date.now() + SERVER_READY_TIMEOUT_MS;
  while (Date.now() < deadline) {
    try {
      // biome-ignore lint/performance/noAwaitInLoops: sequential polling until the dev server responds
      const response = await fetch(baseUrl, { method: "HEAD" });
      if (response.ok || response.status === 404) {
        return;
      }
    } catch {
      // server not up yet
    }
    await delay(POLL_INTERVAL_MS);
  }
  throw new Error(
    `Dev server did not become ready within ${SERVER_READY_TIMEOUT_MS}ms`
  );
}

function startDevServer() {
  const child = spawn("bun", ["run", "next", "dev", "--port", String(PORT)], {
    env: { ...process.env, PLAYWRIGHT: "true" },
    stdio: "inherit",
  });
  return {
    baseUrl: `http://127.0.0.1:${PORT}`,
    stop: () => {
      child.kill("SIGTERM");
    },
  };
}

type LinkRect = {
  href: string;
  label: string;
  x: number;
  y: number;
  width: number;
  height: number;
};

function formatLinksFile(pages: LinkRect[][]): string {
  const body = JSON.stringify(pages, null, 2);
  return `// Generated by scripts/generate-cv-v2-textures.ts — do not edit by hand.
// Run \`bun run cv:textures\` after editing components/cv-v2/cv-sheets.tsx.
//
// Hit-rects (CSS px, relative to each page's top-left) for every <a> in
// the rendered CV, used to overlay real, focusable links on top of the
// paper texture in the /cv-v2 WebGL scene.

export type CvLinkRect = {
  href: string;
  label: string;
  x: number;
  y: number;
  width: number;
  height: number;
};

export const CV_LINK_RECTS: CvLinkRect[][] = ${body};
`;
}

async function render(baseUrl: string) {
  await mkdir(OUTPUT_DIR, { recursive: true });
  const browser = await chromium.launch();
  try {
    const page = await browser.newPage({
      deviceScaleFactor: TEXTURE_SCALE,
      viewport: { height: 1400, width: 1200 },
    });
    await page.goto(`${baseUrl}${SHEETS_PATH}`, {
      timeout: PAGE_LOAD_TIMEOUT_MS,
      waitUntil: "networkidle",
    });
    const sheets = await page.locator(".page").all();
    if (sheets.length !== 2) {
      throw new Error(`Expected 2 .page sheets, found ${sheets.length}`);
    }
    const linkRects: LinkRect[][] = [];
    for (const [index, sheet] of sheets.entries()) {
      // biome-ignore lint/performance/noAwaitInLoops: sequential per-sheet capture keeps memory flat
      await sheet.screenshot({
        path: resolve(OUTPUT_DIR, `page-${index + 1}.png`),
      });
      const pageBox = await sheet.boundingBox();
      if (!pageBox) {
        throw new Error(`Sheet ${index + 1} has no layout box`);
      }
      const anchors = await sheet.locator("a").all();
      const rects: LinkRect[] = [];
      for (const anchor of anchors) {
        // biome-ignore lint/performance/noAwaitInLoops: handful of links per page, order doesn't matter for correctness but keeps output stable
        const box = await anchor.boundingBox();
        const href = await anchor.getAttribute("href");
        const label = (await anchor.innerText()).trim();
        if (!(box && href && label)) {
          continue;
        }
        rects.push({
          height: box.height,
          href,
          label,
          width: box.width,
          x: box.x - pageBox.x,
          y: box.y - pageBox.y,
        });
      }
      linkRects.push(rects);
    }
    await writeFile(LINKS_FILE, formatLinksFile(linkRects));
  } finally {
    await browser.close();
  }
}

async function main() {
  if (externalBaseUrl) {
    await waitForServer(externalBaseUrl);
    await render(externalBaseUrl);
    return;
  }
  const server = startDevServer();
  try {
    await waitForServer(server.baseUrl);
    await render(server.baseUrl);
  } finally {
    server.stop();
  }
}

await main();
