// Generated by scripts/generate-cv-v2-textures.ts — do not edit by hand.
// Run `bun run cv:textures` after editing components/cv-v2/cv-sheets.tsx.
//
// Hit-rects (CSS px, relative to each page's top-left) for every <a> in
// the rendered CV, used to overlay real, focusable links on top of the
// paper texture in the /cv-v2 WebGL scene.

export type CvLinkRect = {
  href: string;
  label: string;
  x: number;
  y: number;
  width: number;
  height: number;
};

export const CV_LINK_RECTS: CvLinkRect[][] = [
  [
    {
      "height": 18.84375,
      "href": "/portfolio?code=",
      "label": "connorforsyth.co/portfolio?code=",
      "width": 201.109375,
      "x": 233.78125,
      "y": 160
    },
    {
      "height": 18.84375,
      "href": "https://linkedin.com/in/connorforsyth",
      "label": "linkedin.com/in/connorforsyth",
      "width": 179.21875,
      "x": 233.78125,
      "y": 185.84375
    },
    {
      "height": 18.84375,
      "href": "mailto:c@connorforsyth.co",
      "label": "c@connorforsyth.co",
      "width": 122.40625,
      "x": 58.78125,
      "y": 211.6875
    },
    {
      "height": 18.84375,
      "href": "https://github.com/connorforsyth",
      "label": "github.com/connorforsyth",
      "width": 155.875,
      "x": 233.78125,
      "y": 211.6875
    },
    {
      "height": 18.84375,
      "href": "https://www.deloitte.com.au",
      "label": "Deloitte Australia",
      "width": 100.34375,
      "x": 217.0625,
      "y": 284.375
    },
    {
      "height": 18.84375,
      "href": "https://designit.com",
      "label": "Designit",
      "width": 48.515625,
      "x": 216.78125,
      "y": 384.25
    },
    {
      "height": 18.84375,
      "href": "https://www.tedxmelbourne.com",
      "label": "TEDxMelbourne",
      "width": 96.859375,
      "x": 207.71875,
      "y": 630.03125
    },
    {
      "height": 18.84375,
      "href": "https://www.sydney.edu.au",
      "label": "Design Lab: University of Sydney",
      "width": 198.546875,
      "x": 251.609375,
      "y": 748.75
    },
    {
      "height": 18.84375,
      "href": "https://www.civic.org.au",
      "label": "Civic Disability Services",
      "width": 142.65625,
      "x": 153.25,
      "y": 822.78125
    },
    {
      "height": 18.84375,
      "href": "https://www.blp.com.au",
      "label": "Billard Leece Partnership",
      "width": 149,
      "x": 242.640625,
      "y": 952
    }
  ],
  []
];
